---
# INSTALL .: `pre-commit install --overwrite --install-hooks`
# UPDATE ..: `pre-commit autoupdate`

default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # Generall Stuff
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: end-of-file-fixer
      # VCS
      - id: check-merge-conflict
      # Config / Data Files
      - id: check-yaml
      # Python
      - id: debug-statements
      - id: requirements-txt-fixer
  # Prettier (HTML, JS, CSS, Markdown…)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.1
    hooks:
      - id: prettier
        types:
          - css
          - html
          - javascript
          - markdown
  # YAML
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.1
    hooks:
      - id: yamllint
  # Python: check syntax
  - repo: https://github.com/life4/flakehell
    rev: v.0.8.0
    hooks:
      - id: flakehell
  # Python: reorder imports
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
      - id: reorder-python-imports
        args:
          - "--application-directories=.:src:tests"
          - "--separate-relative"
          - "--py26-plus"
  # Python: lint with black
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        args:
          - "--line-length=88"
          - "--target-version=py27"
