---
# INSTALL .: `pre-commit install --overwrite --install-hooks`
# UPDATE ..: `pre-commit autoupdate`

default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      # Generall Stuff
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      # VCS
      - id: check-merge-conflict
      # Config / Data Files (syntax check only)
      - id: check-yaml
      - id: check-toml
      # Python
      - id: debug-statements
      - id: requirements-txt-fixer
  # Prettier (HTML, JS, CSS, Markdown, YAML…)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
  # Python: check syntax
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - "--select=F"
  # Python: reorder imports
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        args:
          - "--application-directories=.:src:tests"
          - "--separate-relative"
          - "--py26-plus"
  # Python: lint with black
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        args:
          - "--line-length=88"
          - "--target-version=py27"
