name: coverage

on:
  push:
    branches:
      - main

jobs:
  coveralls:
    name: send coverage report to coveralls.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: >-
          pip install
          -c requirements/constraints.txt
          -r requirements/tests.in
          coveralls
          .
      - name: Get coverage
        run: coverage run -m unittest discover
      - name: Show report
        run: coverage report
      - name: send report to coveralls
        run: coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.COVERALLS_GITHUB_TOKEN }}
