name: test

on:
  - push
  - pull_request

jobs:
  tests:
    name: run tests with tox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "2.7"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: >-
          pip install
          -r requirements/ci.txt
          tox-gh-actions
      - name: Run tox
        run: tox
